FROM node:24.13.0-alpine

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@10.29.2 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]