FROM golang:1.25.6-alpine

WORKDIR /app

# Install git & air (hot reload)
RUN apk add --no-cache git \
    && go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air"]